version: "3.8"

networks:
  chat-helper:
    driver: bridge

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - chat-helper

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - chat-helper
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
    networks:
      - chat-helper
    depends_on:
      - backend

volumes:
  dbdata6:
